name = "sej-clone"
type = "javascript"
main = "dist/index.js"
compatibility_date = "2024-04-01"

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx"]

[env.production]
routes = [
  { pattern = "seorankerai.com", zone_name = "seorankerai.com" },
  { pattern = "*.seorankerai.com", zone_name = "seorankerai.com" }
]

[triggers.crons]
crons = ["0 0 * * *"]
